### ISSUE TITLE
Hardware in the Loop Setup

### ISSUE THREAD

**Issue by a-poduval** [harvard-edge/airlearning-rl#5]
We have been trying to set this up on a Jetson TX2. What we've done so far:

1) Installed and followed setup for this package on the Jetson.
2) Set up the AirLearning UE4 package on a desktop.

What has worked so far:
Manually running the UE4 environment generator project on the desktop and then trying the move.py sanity test with the desktop's IP from test_suites on the Jetson.

What we've faced issues with - on running collect_data.py, we got an error. This is because the default configuration tries to start the game and launch the exes for the training phase, which can only be done if this is also run on the Desktop.

We are yet to try running inference on the Jetson. We will update our findings on this page after saving a trained model and running it on the Jetson.

**Comment by a-poduval** [comment]
Quick update: After commenting the start_game task out and fixing some issues with the shared directory paths, there wasn't any major trouble, the Jetson could connect to the PC and start the reinforcement learning tasks. If needed, after more extensive testing, I could post an update if I run into any further issues. Otherwise, I think we can close this.

One minor issue: the copy_json_to_server function in common/utils.py needs to see a slight change. It needs to be protected under an if statement to something like

if(os.name=="nt"): 
    exit_code = os.system("copy " + filename + " " + settings.unreal_host_shared_dir)
else:
    exit_code = os.system("cp " + filename + " " + settings.unreal_host_shared_dir)

**Comment by srivatsankrishnan** [comment]
Good to know it resolved your issue. Feel free to open it if you run into a similar issue again.
